gerror: Add support for marshaling GError from Python to C
Refactor pygi_gerror_exception_check() to use a new broken out function
pygi_error_marshal_from_py(). This allows re-use for argument marshaling
of a Python GError to a C GError.
Remove PYGI_META_ARG_TYPE_CHILD setting for GError out argument marshaling.
This was incorrect since GError exception arguments are not specified
explicitly and instead uses the "throws" option.

https://bugzilla.gnome.org/show_bug.cgi?id=685197